name: FakePlayersPM4
version: 4.18-PM4
author: Thor
description: A plugin made to spawn fake players by xPrim69x!
website: https://www.github.com/ThorMagHunde
main: xPrim69x\FakePlayers\Main
api: 4.0.0
permissions:
  fakeplayers.spawn:
    description: Permission to spawn a fake player and use the /fp command.
    default: op
